### ISSUE TITLE
请问您是手动录入dict的么？

### ISSUE THREAD

**Issue by dqwyy** [Kahaani/dieghv#10]
您好，感谢您制作了这么一套优秀的输入方案。不过我有一点比较好奇，您是怎么录入dict文件的？是拿字典手动一个一个录入的么？

**Comment by kahaani** [comment]
是手工录入的。有个小窍门：从《潮州音字典》后面的音序检字表录入，比从字典正文里找注音快，缺点是多音字不能按词语区分读音。
