### ISSUE TITLE
default.custom.yaml 在哪裏下載？

### ISSUE THREAD

**Issue by hoist1999** [Kahaani/dieghv#8]

**Comment by kahaani** [comment]
在[网盘](http://pan.baidu.com/s/1kUJt5JL)的 Linux、macOS、iOS 文件夹里都有对应的`default.custom.yaml`文件。

**Comment by CharKwayTeow** [comment]
安裝Rime之後就看有`default.custom.yaml`，但是需要家己修改添加潮語輸入法。
@Kahaani 是否可以把建議的`default.custom.yaml`內容放到wiki，方便大家人直接複製？

**Comment by kahaani** [comment]
@CharKwayTeow 是指 GitHub Wiki 吗？放在网盘也还行吧，和安装程序在一起。

**Comment by CharKwayTeow** [comment]
@Kahaani 感覺把release放在第三方網站唔是一個好選擇，是否可以在github創建一個release，再放鏈接出去？
